name: PR Agent Automated Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run PR Agent
        uses: the-pr-agent/pr-agent@v0.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.PR_AGENT_TOKEN }}

          config.model: "ollama/minimax-m3:cloud"
          config.fallback_models: '["ollama/nemotron-3-ultra:cloud"]'
          config.custom_model_max_tokens: "4000"
          config.max_diff_tokens: "32000"

          OLLAMA.API_KEY: ${{ secrets.OLLAMA_API_KEY}}
          OLLAMA.API_BASE: "https://ollama.com"

          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "synchronize"]'
